### ISSUE TITLE
/config and /state sending "ERROR:404 Not Found" 

### ISSUE THREAD

**Issue by Lodhar** [ljalves/hfeasy#35]
Hi everyone,

So, I have two HF-LPB100 (Chacon). The upload page is showing (iweb.html) but not the rest. I used that last page to update HFEASY_WEB_UPGRADE and then HFEASY_SERIAL_UPGRADE. But the url context /config, /state and /timer, all return a "ERROR:404 Not Found" exception. Did I do something wrong?

Some more details:
![image](https://user-images.githubusercontent.com/7315517/166232804-145d8584-e861-4df9-8669-506f3a9225a3.png)

**Comment by maxiido** [comment]
Hi,
as far as I know the HFEASY_SERIAL_UPGRADE is only for upgrading via a serial wired connection. So I guess you only need to upload the HFEASY_WEB_UPGRADE file in the Upgrade SW menu. And use the  „upgrade application“ section instead of the web page upgrade like mentioned here: https://github.com/ljalves/hfeasy/issues/21#issuecomment-1023890083 
At least thats how it worked for me on my LPB130 with Edge as browser.

**Comment by Lodhar** [comment]
Thanks for your answer! I will try that.

**Comment by Lodhar** [comment]
I see it's still open. It worked but you need to flash with Edge (Firefox says it works but it doesn't). 
Go to http://[ip]/iweb.html
You need to use the "Upgrade application" not "Upgrade customized web page".
And upgrade with HFEASY_WEB_UPGRADE.bin
